### ISSUE TITLE
Suggestion for notes of req 2/n

### ISSUE THREAD

**Issue by GregoireHENRY** [anise-toolkit/meeting-notes#3]
Also, do you think this should be added to the [meeting notes](9bb50300b6d9c80c9763714fbab39e7da20d4ae8) ?

+ *ready* requirements move to *approved* when basic implementation is suggested and accepted

**Comment by ChristopherRabotin** [comment]
Yes, that's a good idea

**Comment by ChristopherRabotin** [comment]
I think this is closed, right?

**Comment by GregoireHENRY** [comment]
yeah 😅
